services:
  
  backend:
    build:
      context: ./employee-management-backend  # Path to your backend directory
    ports:
      - "5000:5000"  # Exposes port 5000
    environment:
      - NODE_ENV=development
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=nSREE@2911#
      - DB_NAME=employeeDB
    depends_on:
      - db

  db:
    image: mysql:8.0  # MySQL image
    environment:
      - MYSQL_ROOT_PASSWORD=nSREE@2911#
      - MYSQL_DATABASE=employeeDB
    ports:
      - "3307:3306"  # Exposes MySQL port
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
